name: ItemEconomy
version: ${project.version}
main: shallowcraft.itemeconomy.Core.ItemEconomy
api-version: 1.16
authors: [ BlackShadow2941 ]
description: An item based economy for minecraft with potential for vault support
depend: [Vault]
commands:
  create_account:
  balance:
  list_accounts:
  create_account_all:

