name: ItemEconomy
version: ${project.version}
main: shallowcraft.itemeconomy.ItemEconomy
api-version: 1.16
authors: [ BlackShadow2941 ]
description: An item based economy for minecraft with potential for vault support
depend: [Vault]
commands:
  ItemEconomy:
    aliases: [ie, IE, itemeconomy, money, eco, economy]
    usage: |
      /ItemEconomy balance
      /ItemEconomy baltop
      /ItemEconomy create_account <name>
      /ItemEconomy list_accounts
      /ItemEconomy create_account_all
      /ItemEconomy reload
      /ItemEconomy save
      /ItemEconomy remove_account <name>
      /ItemEconomy deposit <name> <amount>
      /ItemEconomy withdraw <name> <amount>
  Tax:
    aliases: [tax, ietax, ieTax, taxes, t]
    usage: |
      /Tax tax <name> <[optional] tax name>
      /Tax add_tax <name> <tax name> <rate>
      /Tax remove_tax <name> <tax name>
      /Tax tax_info <name> < [optional] tax name>
      /Tax tax_all
      /Tax clear_tax <name>
permissions:
  itemeconomy.admin:
    default: op
  itemeconomy.message:
    default: true

